# Generated by Django 5.1.4 on 2025-01-10 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_characteres'),
    ]

    operations = [
        migrations.AddField(
            model_name='characteres',
            name='eyecolors',
            field=models.CharField(default='Desconhecida', max_length=100),
        ),
        migrations.AddField(
            model_name='characteres',
            name='haircolor',
            field=models.CharField(default='Desconhecida', max_length=100),
        ),
        migrations.AddField(
            model_name='characteres',
            name='img',
            field=models.TextField(blank=True, null=True, verbose_name='https://pbs.twimg.com/profile_images/1083038156436525057/oc7dOkJw_400x400.jpg'),
        ),
        migrations.AddField(
            model_name='characteres',
            name='species',
            field=models.CharField(default='Desconhecida', max_length=100),
        ),
        migrations.AddField(
            model_name='characteres',
            name='wizard',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='characteres',
            name='house',
            field=models.CharField(default='Desconhecida', max_length=100),
        ),
        migrations.AlterField(
            model_name='characteres',
            name='name',
            field=models.CharField(default='Desconhecida', max_length=100),
        ),
    ]
