# Generated by Django 5.1.4 on 2025-01-10 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_characteres_eyecolors_characteres_haircolor_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Characteres',
            new_name='Characters',
        ),
    ]
